### ISSUE TITLE
Design a Interactive Readme file Which Representing Our Repo 

### ISSUE THREAD

**Issue by rahulkamilya** [rahulkamilya/excoders#14]
Make Sure You Can Star Our Repo 🌟 before Start !

**Comment by Arya-n-101** [comment]
assign this to me

**Comment by rahulkamilya** [comment]
OK @Arya-n-101 , but Make Sure You Can Star Our Repo 🌟 before Start !

**Comment by loan-mgt** [comment]
@Arya-n-101 To be clear it is not mandatory to star the repo to contribute
