### ISSUE TITLE
Screenshots  App Screenshot missing

### ISSUE THREAD

**Issue by loan-mgt** [rahulkamilya/excoders#15]
The screenshot link at the end of the readme is broken

The goal: of the screenshot as to illustrate the app

The solution: make a new screenshot and update the readme OR fix the screenshot link if already exists

**Comment by rahulkamilya** [comment]
> The screenshot link at the end of the readme is broken
> 
> The goal: of the screenshot as to illustrate the app
> 
> The solution: make a new screenshot and update the readme OR fix the screenshot link if already exists

I didn't Get you @Qypol342 
Can you Specify with image

**Comment by nrj-kmr** [comment]
- Maybe he is saying about the screenshot link in readme file of this repository, whose alternate text is : "App Screenshot".
- Which is in the end section of readme.md file.

![Screenshot from 2023-10-02 15-37-11](https://github.com/rahulkamilya/excoders/assets/93479597/5130422c-a64d-46c3-a065-53af0cd5eed1)

**Comment by rahulkamilya** [comment]
> * Maybe he is saying about the screenshot link in readme file of this repository, whose alternate text is : "App Screenshot".
> * Which is in the end section of readme.md file.
> 
> ![Screenshot from 2023-10-02 15-37-11](https://user-images.githubusercontent.com/93479597/271942205-5130422c-a64d-46c3-a065-53af0cd5eed1.png)

got it @Qypol342 ,
Thanks @nrj-kmr 


For this, I already Raised a Issue regarding readme file @Qypol342

**Comment by loan-mgt** [comment]
@rahulkamilya  ok !

**Comment by loan-mgt** [comment]
duplicate 
#14
