### ISSUE TITLE
Add a Hamburger Style Navbar for Mobile

### ISSUE THREAD

**Issue by rahulkamilya** [rahulkamilya/excoders#2]
Add a Hamburger Style Navbar for Mobile View 📲

It's a Team Portfolio Website, You can Contribute here for "Hacktoberfest2023"

I'II Marge it by hacktoberfest-accepted

Happy Hacking (:

**Comment by shreverr** [comment]
Hi @rahulkamilya ,
I want to contribute to this issue.
Should I add an index.js file or code in script tag?

**Comment by gamandeepsingh** [comment]
hey! Could you Please assign me the role for the same !!

**Comment by rahulkamilya** [comment]
ok I assigned both @shreverr @gamandeepsingh of you
