### ISSUE TITLE
uneven alignment of footer

### ISSUE THREAD

**Issue by amul67142** [rahulkamilya/excoders#24]
![Screenshot (22)](https://github.com/rahulkamilya/excoders/assets/73737660/ec4295c9-643b-446e-88e9-9e5abaa60f6c)

There is a issue in the footer.

i can fix this.

**Comment by amul67142** [comment]
please assign this issue to me under hacktober fest.

**Comment by rahulkamilya** [comment]
@amul67142 , Assigned

Make sure you star 🌟 our repo
