### ISSUE TITLE
Review UI  

### ISSUE THREAD

**Issue by Dhruvrode** [rahulkamilya/excoders#29]
Issue: 
The current review section doesnt look good and it is mix up with bg colour

Solution:
We can improve the UI of the review by adding card and animations..

**Comment by Dhruvrode** [comment]
Hey @rahulkamilya  I Can fix this and improve the UI of review section please assign me.
I am contributing for HackToberfest :)

**Comment by rahulkamilya** [comment]
@Dhruvrode Star this Repo 🌟

**Comment by Dhruvrode** [comment]
I have stared the repo , Tysm.

**Comment by Dhruvrode** [comment]
Hey @rahulkamilya  I have made the necessary PR for this issue .Make sure to label the PR with hacktoberfest-accepted after reviewing it.  #30   And please inform me if I have made a mistake with how PRs are usually done since it is my first time.

**Comment by Dhruvrode** [comment]
Hey @rahulkamilya  i wanted to know if  my issue is merged or not . cuz in my hacktoberfest it says waiting what does this mean can you kindly inform me about it?
