### ISSUE TITLE
Home Page Changes

### ISSUE THREAD

**Issue by Dhruvrode** [rahulkamilya/excoders#31]
Hey @rahulkamilya  I wanted to contribute more to this repo. 

Issue:
Home page directly have review section and something is missing!

solution:
I can add some images with indicators to it and you can change the image whatever your website fits or you share the images with me i will put .

I Can also change headers logo like i can add some animation in logo of header

**Comment by Dhruvrode** [comment]
Hey @rahulkamilya  Please assign me i would love to contribute :)

**Comment by Dhruvrode** [comment]
Tysm :)

**Comment by rahulkamilya** [comment]
> Hey @rahulkamilya  Please assign me i would love to contribute :)

@Dhruvrode Assigned 💐

**Comment by Dhruvrode** [comment]
Hey @rahulkamilya  I have made the neccessary PR for the issue . #32  please dont forget to add Hacktober-accepted label on my PR. If  you need any changes or i had make mistake you can tell me i will solve that .
Thank you!

**Comment by anushkapal28** [comment]
Hello! I'm interested in working on this task. I have experience with HTML and CSS , and I'm eager to contribute. Please consider assigning this to me, and I'll get started right away. Thanks! I will make a worthful contribution.
