### ISSUE TITLE
Add Preloader to the Landing page

### ISSUE THREAD

**Issue by trishanu-init** [rahulkamilya/excoders#36]
A Preloader should be added to the landing page so that on slow network speeds an animation is shown while the page is loaded.

https://github.com/rahulkamilya/excoders/assets/85580785/00c53f8b-61cf-45f1-a4d2-1fc94d53959e

**Comment by trishanu-init** [comment]
@rahulkamilya Please assign this issue to me with the hacktoberfest label

**Comment by rahulkamilya** [comment]
@trishanu-init 🌟 The Repo

**Comment by trishanu-init** [comment]
@rahulkamilya PR done 👍
