### ISSUE TITLE
Add a Projects.html page

### ISSUE THREAD

**Issue by rahulkamilya** [rahulkamilya/excoders#4]
Add a Projects.html page , When anybody click the projects, They are able to see different projects

**Comment by Rohit-sharma04** [comment]
i would like to contribute for this issue ,could you please assign it to me

**Comment by rahulkamilya** [comment]
Okky do it @Rohit-sharma04

**Comment by Rohit-sharma04** [comment]
do i have to use dummy data for the  projects

**Comment by rahulkamilya** [comment]
No problem @Rohit-sharma04
